{"name": "Invalid value for param - instructions in the Request Body and getting Incorrect output -- @1.5 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628277071303, "stop": 1628277071304}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628277071305, "stop": 1628277071306}, {"name": "When Set invalid request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [1, 0] ], \"instructions\" : \"NNESEESWNWW\", \"instructions\" : \"NESW\" }", "status": "passed", "start": 1628277071306, "stop": 1628277071307}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628277071307, "stop": 1628277071322}, {"name": "Then I receive error 500, \"Internal Server Error\"", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628277071322, "stop": 1628277071324}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [1, 0] ], \"instructions\" : \"NNESEESWNWW\", \"instructions\" : \"NESW\" }"}, {"name": "response_code", "value": "500"}, {"name": "response_error", "value": "Internal Server Error"}], "start": 1628277071300, "stop": 1628277071325, "uuid": "4730f32a-4dd5-4638-abd6-6474b3fdfe30", "historyId": "b39501814517688743bf40218d17c895", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Instructions params: Invalid value for param - instructions in the Request Body and getting Incorrect output", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Instructions params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}