{"name": "Invalid value for param - instructions in the Request Body and getting Incorrect output -- @1.5 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628184045102, "stop": 1628184045103}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628184045103, "stop": 1628184045104}, {"name": "When Set invalid request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [1, 0] ], \"instructions\" : \"NNESEESWNWW\", \"instructions\" : \"NESW\" }", "status": "passed", "start": 1628184045104, "stop": 1628184045105}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628184045105, "stop": 1628184045118}, {"name": "Then I receive error 500, \"Internal Server Error\"", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628184045119, "stop": 1628184045120}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [1, 0] ], \"instructions\" : \"NNESEESWNWW\", \"instructions\" : \"NESW\" }"}, {"name": "response_code", "value": "500"}, {"name": "response_error", "value": "Internal Server Error"}], "start": 1628184045100, "stop": 1628184045122, "uuid": "c08cf7f8-8df6-4c5e-b07b-bfe7befa3c20", "historyId": "b39501814517688743bf40218d17c895", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Instructions params: Invalid value for param - instructions in the Request Body and getting Incorrect output", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Instructions params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}