{"name": "Invalid value for param - Patches in the Request Body and getting Incorrect output -- @1.5 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 3], 'patches': 1}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628433427411, "stop": 1628433427411}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628433427411, "stop": 1628433427413}, {"name": "When Set invalid request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [[-2, -2]], \"instructions\" : \"NNESEESWNWW\" }", "status": "passed", "start": 1628433427413, "stop": 1628433427414}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628433427414, "stop": 1628433427427}, {"name": "Then I receive error 500, \"Internal Server Error\"", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 3], 'patches': 1}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628433427428, "stop": 1628433427430}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [[-2, -2]], \"instructions\" : \"NNESEESWNWW\" }"}, {"name": "response_code", "value": "500"}, {"name": "response_error", "value": "Internal Server Error"}], "start": 1628433427409, "stop": 1628433427431, "uuid": "9c4b8307-a624-48b3-9b58-1ee60d011a8d", "historyId": "2d93ffd4a744487f6a74a5b920ccb8e1", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: Invalid value for param - Patches in the Request Body and getting Incorrect output", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}