{"name": "One of the coordinate value is '0' for param - patches in the Request Body -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628433427532, "stop": 1628433427532}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628433427533, "stop": 1628433427534}, {"name": "When Set request Body { \"roomSize\" : [5,5], \"coords\" : [1, 2], \"patches\" : [[1, 0]], \"instructions\" : \"NEWSNEWS\" }", "status": "passed", "start": 1628433427534, "stop": 1628433427535}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628433427535, "stop": 1628433427548}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628433427548, "stop": 1628433427549}, {"name": "And Response BODY with the right data [1, 2] and 0", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628433427549, "stop": 1628433427551}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5,5], \"coords\" : [1, 2], \"patches\" : [[1, 0]], \"instructions\" : \"NEWSNEWS\" }"}, {"name": "coords", "value": "[1, 2]"}, {"name": "patches", "value": "0"}], "start": 1628433427530, "stop": 1628433427553, "uuid": "9ff3c1ab-44a6-480c-b2e4-01d5cedfe53e", "historyId": "028cd67d9a9b5535eb9967afe78f2431", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: One of the coordinate value is '0' for param - patches in the Request Body", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}